### ISSUE TITLE
search_submissions just seems to repeat same 500 submission ID's

### ISSUE THREAD

**Issue by karigunnarsson** [dmarx/psaw#27]
I've been trying to run this code:

```
api = psaw.PushshiftAPI()

thread_list = list(api.search_submissions(after=1501682599,
                                         subreddit='dota2',
                                         filter=['title', 'id', 'score'],
                                         score = ">100"))
```

which gives me back a list of ~125.000 submissions as of today, but of those there are only 500 unique submission ID's, which is the same as the batch-size in PSAW as far as i've gathered.

It seems to always populate at around 120.000 items in the list, regardless of what score filter i use, but as i said, it just seems to fetch the same 500 threads again and again (the first 500 in chronological order from what i can tell, starting at the "after" date).

**Comment by dmarx** [comment]
Hi Kari,

Sorry for the inconvenience. Here's what's going on: pushshift currently only supports using dates for paging, and psaw currently assumes you are going backwards in time. I.e. it doesn't respect the `after` parameter properly, as you're observing. 

The issue you're experiencing is related to a known issue with sorting functionality. When you provide only an "after" parameter, pushshift inverts the sort and feeds you content from the after date forwards. psaw then grabs the last returned item and uses its created_utc to add a "before" search argument, so your search ends up bounded between your target date and the creation date of the 500th submission in the resultset.

**Temporary fix 1**  
Add the argument `sort='desc'`. This will tell pushshift to return content in the order psaw expects, and the result should be that your after date will become a stop condition. 

**Temporary fix 2**  
Another person submitted a pull request to make psaw better respect sort which I haven't yet merged: try installing [their fixed version](https://github.com/robhawkins/psaw) and add `sort='asc'` to your query. Pushshift is already using an ASC sort in its response, but psaw doesn't know that (and this issue will stay open until that's fixed!). So if you use @robhawkins' version which supports paging with ASC sort and tell psaw that that's what you want, psaw should use the last item in its response to update the `after` parameter instead of `before`, giving you the desired results.

One last point of clarification: you're probably only going to see results up to a month or two ago. Pushshift perpetually scrapes new content and doesn't go back to check for an updated score for about a month. This means that nearly all of the past month's worth of content will have a score of 1. If you want recent content as well, initialize your PushshiftAPI instance with a praw.Reddit instance, drop the "score" filter, and search for submissions going back as far as you need to backfill: psaw will grab the ids from pushshift and then download the actual content directly from reddit with praw, giving you up-to-date scores. You can then filter low-scoring content from the result set as they come in.

**Comment by pushshift** [comment]
Hey there -- This has been an ongoing issue with some drawbacks from how the indexes were first set up.  The next Pushshift API version will support paging by id.  There are some issues with some older posts / comment ids on Reddit where they aren't always sequential with respect to time (but this is usually the exception and not the rule).

I think it may be possible to add a before_id and after_id parameters to the current API -- I just need to test the performance of how ES handles it.  

I'll look at this today and over the weekend and try to come up with a solution (the next API release will probably be in a month or so -- but if this is a low effort fix, I'll definitely add it.)

Also -- for scores, that is correct.  Currently scores aren't updated within the API but that is going to change very soon.  I have the code in place to handle re-crawling to update scores -- I just need to test things to make sure I don't break anything else.  

So to clarify:

1)  I'll check if adding paging and sorting by id is possible (not too expensive internally) and if it is an easy addition, I'll add that.

2)  Updates for scores will also be coming soon.  Currently there is a "retrieved_on" parameter.  Technically, the meaning of that will be altered slightly to mean "first_seen_on."  I'll still keep the parameter name as I don't want to break anything -- but going forward, any value in retrieved_on should be considered the first time Pushshift saw that object.  A new field called "updated_on" will be an epoch int field that will show the time that the object was updated.  If the object was never updated, that field will be null.

If you have any suggestions or comments on these plans, please let me know!

**Comment by karigunnarsson** [comment]
Ahh great, that makes it work, thanks David :)

**Comment by dmarx** [comment]
Fixed in latest release.
