### ISSUE TITLE
Attribute error 'str' object has no attribute 'id'

### ISSUE THREAD

**Issue by e421124124sa** [dmarx/psaw#40]
Traceback (most recent call last):
      File "run1.py", line 718, in <module>
        run_bot(r, comments_replied_to)
      File "run1.py", line 671, in run_bot
        subs_interacted = int(len(list(submissions_subs))) + int(len(list(comments_subs)))
      File "/usr/local/lib/python3.5/dist-packages/psaw/PushshiftAPI.py", line 284, in _praw_search
        fullnames = [prefix + c.id for c in batch]
      File "/usr/local/lib/python3.5/dist-packages/psaw/PushshiftAPI.py", line 284, in <listcomp>
        fullnames = [prefix + c.id for c in batch]
    AttributeError: 'str' object has no attribute 'id'

It seems like the underlying issue is with PSAW rather than my script as the attribute error is referring to a call not within my script? 

Here's the relevent code for line 671.

        comments_subs = api.search_comments(author=(tmpuser), aggs='subreddit')
        submissions_subs = api.search_submissions(author=(tmpuser), aggs='subreddit')
        subs_interacted = int(len(list(submissions_subs))) + int(len(list(comments_subs)))

**Comment by dmarx** [comment]
I'm not able to reproduce the error. Can you specify a value for `tmpuser` that will allow me to reproduce this? Also, did you initialize `api` with or without a `praw.Reddit` instance? I can't really help you address what's wrong without being able to reproduce it. 

That said, I think there's a helper function you can use that will accomplish what you are trying to do. Take a look at `api.redditor_subreddit_activity()`. I'd still like to address the underlying issue, but that function should at least unblock you (hopefully).

**Comment by e421124124sa** [comment]
Here are my imports.

    import praw
    from psaw import PushshiftAPI

`tmpuser` is just the name of a user which I am unable to share here. For an example, if you were a redditor in question, `tmpuser = 'dmarx'`; `tmpuser` is essentially the same as adding any reddit username in a string

**Comment by dmarx** [comment]
1. Still not able to reproduce the error, please give me a complete code snippet that reliably generates the error.
2. Pretty sure you're not doing what you think you are. By not providing the functions with a `limit=0` argument, the count you are performing is actually the total # of comments + total # of submissions + 2.  The result of the "aggs" call will be the first item returned by the generator, the following items will be comments/submissions. This is why the demo for aggs functionality invokes `next(gen)`.
3. Have you looked at `api.redditor_subreddit_activity` like I suggested? Pretty sure that's what you need.
4. Although I'm not reproducing your error on my end, it's strange to me that you're passing the author name as `author=(tmpuser)` rather than `author=tmpuser`. It's not throwing your error on my end, but this might be a contributing factor to whatever problem you're having. `author` should be a string, not a tuple.

**Comment by e421124124sa** [comment]
Thanks for the reply; I'm looking to get the number of unique subreddits posted/commented to. Assuming the current code will return the subreddits for the comments/posts, it should add the two together and give that value. 

For example, If i made 5 comments and 5 posts total. 3 of those comments were on subreddit `A`, 2 other comments were on subreddit `B` and `C`. 3 of the posts were on `D` with the last two being on `E` and `F`. `subs_interacted` should return `6`

**Comment by e421124124sa** [comment]
I should note swapping `aggs='subreddit'` with `aggs='id'` solved the issue. If you are unable to reproduce the issue, there is nothing I can provide further. Hopefully this will help you solve the issue.
